{"name": "Test Registration with Invalid Data", "status": "broken", "statusDetails": {"message": "AttributeError: 'NoneType' object has no attribute 'is_displayed'", "trace": "self = <paraBank_test.TestParaBank object at 0x0000018F2211CCD0>\n\n    @allure.title(\"Test Registration with Invalid Data\")\n    def test_register_user_with_invalid_data(self):\n        self.pb.click_register()\n        self.pb.add_customer_details(\n            first_name=\"Jane\",\n            last_name=\"Doe\",\n            address=\"456 Oak St\",\n            city=\"Springfield\",\n            state=\"IL\",\n            zip_code=\"62701\",\n            phone=\"555-5678\",\n            ssn=\"\",\n            username=\"\",\n            password=\"\"\n        )\n        self.pb.click_register_button()\n        with allure.step(\"Verify error message for invalid registration\"):\n            sleep(5)\n>           assert self.pb.get_element(self.pb.Locators.ERROR_USERNAME).is_displayed(), \"Error message not found\"\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE           AttributeError: 'NoneType' object has no attribute 'is_displayed'\n\ntestcases\\paraBank_test.py:64: AttributeError"}, "steps": [{"name": "Clicking on Register link", "status": "passed", "start": 1751093747861, "stop": 1751093749820}, {"name": "Adding customer details: 'Jane' 'Doe'", "status": "passed", "parameters": [{"name": "first_name", "value": "'Jane'"}, {"name": "last_name", "value": "'Doe'"}, {"name": "address", "value": "'456 Oak St'"}, {"name": "city", "value": "'Springfield'"}, {"name": "state", "value": "'IL'"}, {"name": "zip_code", "value": "'62701'"}, {"name": "phone", "value": "'555-5678'"}, {"name": "ssn", "value": "''"}, {"name": "username", "value": "''"}, {"name": "password", "value": "''"}], "start": 1751093749821, "stop": 1751093751218}, {"name": "Clicking on Register button and verifying welcome message", "status": "passed", "start": 1751093751218, "stop": 1751093753515}, {"name": "Verify error message for invalid registration", "status": "broken", "statusDetails": {"message": "AttributeError: 'NoneType' object has no attribute 'is_displayed'\n", "trace": "  File \"C:\\vsCode\\parabank_credentials\\testcases\\paraBank_test.py\", line 64, in test_register_user_with_invalid_data\n    assert self.pb.get_element(self.pb.Locators.ERROR_USERNAME).is_displayed(), \"Error message not found\"\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1751093753515, "stop": 1751093768621}], "attachments": [{"name": "screenshot", "source": "ad1a3f2e-8b24-4ce2-ad3c-08506c08a137-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "9bf19e40-1169-4143-8478-d70863961000-attachment.txt", "type": "text/plain"}], "start": 1751093747861, "stop": 1751093768622, "uuid": "be1e07b9-4e2f-4083-8e72-ac8e335b4bf4", "historyId": "c72fc3edbefed83b6e3076b54585fcc5", "testCaseId": "c72fc3edbefed83b6e3076b54585fcc5", "fullName": "testcases.paraBank_test.TestParaBank#test_register_user_with_invalid_data", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "paraBank_test"}, {"name": "subSuite", "value": "TestParaBank"}, {"name": "host", "value": "Hans"}, {"name": "thread", "value": "14112-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.paraBank_test"}]}